ubihome:
  name: test

logger:
  level: debug
  directory: ./logs

api:

switch:
  - platform: shell
    name: 'Screen'
    id: screen
    command_on: 'wlr-randr --output HDMI-A-1 --on'
    command_off: echo "false" > switch.mock
    # command_state: cat switch.mock
# illuminance:
#   update_interval: 2s

# sensor:
#   - platform: illuminance
#     name: 'Ambient Light'
#     icon: mdi:brightness-6
#     unit_of_measurement: 'lx'
#     device_class: illuminance
#     state_class: measurement

# media_controls:
#   display_entity: media_player.squeezeplay_b8_27_eb_41_84_1c

# event:
#   - platform: media_controls
#     name: test_control